# Generated by Django 5.2.7 on 2026-02-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=100, verbose_name='Schema do tenant')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do cliente')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('currency', models.CharField(default='BRL', max_length=10, verbose_name='Moeda')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Estornado')], default='paid', max_length=10, verbose_name='Status')),
                ('payment_date', models.DateField(verbose_name='Data do pagamento')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referência')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Nota fiscal (anexo)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pagamento de tenant',
                'verbose_name_plural': 'Pagamentos de tenants',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
